import Head from "next/head";
import KdAppBar from "../components/KdAppBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>kinuthiadavid.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kd_io_favicon.ico" />
      </Head>
      <main>
        <KdAppBar />
        index
      </main>
    </div>
  );
}
